---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-demo-ccloud-operator
  namespace: flux-demo
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/mark-christiansen/flux-demo-ccloud-operator

